### ISSUE TITLE
Using relative paths may fail to build correctly

### ISSUE THREAD

**Issue by fer-rum** [fsr/lesson-builder#1]
Using relative paths when calling the builder may cause it to mess up. LaTeX then seems to be passed invalid paths and it fails to build the files. Using absolute paths on the other hand works.

Here are the calls that have shown to fail:

```
fredo in git >  python3 lesson-builder c-lessons
fredo in git >  python3 lesson-builder ./c-lessons
fredo in lesson-builder > python3 __main__.py ../c-lessons/ 
```

**Comment by JustusAdam** [comment]
Fixed it, hope that did not break anything else.
